package com.b2b.common;

public enum WebDriversEnum {
	LOGIN_DRIVER, NEGATIVE_LOGIN_DRIVER, SIGNUP_DRIVER, CLAIM_ACCOUNT_DRIVER, FORGOT_PASSWORD_DRIVER, SEARCH_PLAYER_DRIVER, ADDAMATCH_DRIVER, BROWSE_PLAYERS_DRIVER, PROFILE_PICTURE_DRIVER,
	VALIDATE_STATS_CHANGE_ON_NEW_MATCH_DRIVER, CHANGE_PASSWORD_DRIVER, DELETE_RECENTLY_ADDED_MATCH_DRIVER, VALIDATE_RECENTLY_ADDED_MATCH_DRIVER, NOTIFICATIONS_DRIVER, EDIT_PROFILE_DRIVER, CLUB_LOGO_DRIVER, EDIT_CLUB_INFO;
}
